name: Generate Documentation on Release

on:
  release:
    types: [published]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          
      - name: Set up Python
        run: uv python install
        
      - name: Install dependencies
        run: uv sync
        
      - name: Generate Love2D documentation
        run: uv run main.py --output love2d_docs_${{ github.ref_name }}.txt
        
      - name: Upload documentation to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./love2d_docs_${{ github.ref_name }}.txt
          asset_name: love2d_docs_${{ github.ref_name }}.txt
          asset_content_type: text/plain