name: Generate Documentation on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          
      - name: Set up Python
        run: uv python install
        
      - name: Install dependencies
        run: uv sync
        
      - name: Generate Love2D documentation (concatenated)
        run: uv run main.py --output love2d_docs-${{ github.ref_name }}.txt
        
      - name: Generate Love2D documentation (individual pages)
        run: uv run main.py --output love2d_docs-${{ github.ref_name }}.txt --save-each
        
      - name: List files for debugging
        run: ls -la
        
      - name: Create zip archive of individual pages
        run: |
          FOLDER_NAME="love2d_docs-${{ github.ref_name }}"
          echo "Looking for folder: $FOLDER_NAME"
          ls -la "$FOLDER_NAME"
          cd "$FOLDER_NAME"
          zip -r "../love2d_docs-${{ github.ref_name }}.zip" .
          cd ..
        
      - name: Upload documentation files to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} love2d_docs-${{ github.ref_name }}.txt --clobber
          gh release upload ${{ github.ref_name }} love2d_docs-${{ github.ref_name }}.zip --clobber